// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAD63fiJ3WlVRt4CqqttL-UPb7aY74mW9Y',
    appId: '1:444407118458:web:3ff3c56903a11a9e8bd9c3',
    messagingSenderId: '444407118458',
    projectId: 'inventario-91706',
    authDomain: 'inventario-91706.firebaseapp.com',
    storageBucket: 'inventario-91706.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6BVfOBjHreG0fYZWUKeIuavd5qDYGotg',
    appId: '1:444407118458:android:3d605a38f07003d78bd9c3',
    messagingSenderId: '444407118458',
    projectId: 'inventario-91706',
    storageBucket: 'inventario-91706.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqmZEsPLi0MwsPPub9vzuOKZ-LLUfO-q0',
    appId: '1:444407118458:ios:2cc1773b32a190808bd9c3',
    messagingSenderId: '444407118458',
    projectId: 'inventario-91706',
    storageBucket: 'inventario-91706.firebasestorage.app',
    iosBundleId: 'com.example.inventarioProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBqmZEsPLi0MwsPPub9vzuOKZ-LLUfO-q0',
    appId: '1:444407118458:ios:2cc1773b32a190808bd9c3',
    messagingSenderId: '444407118458',
    projectId: 'inventario-91706',
    storageBucket: 'inventario-91706.firebasestorage.app',
    iosBundleId: 'com.example.inventarioProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAD63fiJ3WlVRt4CqqttL-UPb7aY74mW9Y',
    appId: '1:444407118458:web:6ee11db5ee99382d8bd9c3',
    messagingSenderId: '444407118458',
    projectId: 'inventario-91706',
    authDomain: 'inventario-91706.firebaseapp.com',
    storageBucket: 'inventario-91706.firebasestorage.app',
  );
}
